### ISSUE TITLE
Amazon Lumberyard compatibility ?

### ISSUE THREAD

**Issue by motorsep** [travnick/CryBlend#133]
Are files exported with CryBlend compatible with Amazon Lumberyard ? (which is CryEngine fork, free to use - no subscription)

**Comment by travnick** [comment]
As far as file format used with Amazon Lumberyard is compatible with CryEngine then it's compatible.
We did't test it. Please let us know if you do so.

In the other hand, maybe it's good point of trying to support CryEngine since they said there is full source code and It's based on CryEngine.

**Comment by motorsep** [comment]
Do you have any plans supporting Amazon Lumberyard, since it's free, comes with full source and is more promising than CryEngine EaaS ?

**Comment by travnick** [comment]
I just heard about it from you. So We need to discuss it and check compatibility.

If we have more developers then it's more likely that we will support it.

**Comment by motorsep** [comment]
They just released the engine. I am sure it will take some time for people to adjust to absorb the news :)

One of the first questions on their forums was getting assets out of Blender to Lumberyard.

The adoption rate would depend on docs / samples / support. One major turn off for me in CryEngine was subscription, lack of assets that can be used in production and lack of accessible training materials.

We'll see if Amazon turns that around.

**Comment by niclasschult** [comment]
Technically, CryBlend should work together with Lumberyard, I think, since Lumberyard uses all the CryEngine file formats (cgf etc). Unfortunately, when I tried to export some static geometry using the instructions of the corresponding CryBlend tutorial, I couldn't get it to work. I get the error message 

"0:04 Source control module CryPerforce.dll failed to start (cannot connect to the server?)"

and later

"CStatCGFCompiler::Process: Failed to load geometry file E:\lumberyar
d-1.0-143307e-pc\dev\SamplesProject\Objects\blender\cube\cube.cgf: File E:\lumbe
ryard-1.0-143307e-pc\dev\SamplesProject\Objects\blender\cube\cube.cgf failed to
open for reading"

A DAE-file is generated, but I couldn't generate the cgf no matter what I tried. Since I never worked with CryEngine before, I can not say if this error is a result of me using CryBlend wrongly or if the ResourceCompiler shipped with Lumberyard works somewhat differently than the one shipped with CryEngine itself.

**Comment by ochounos** [comment]
@niclasschult 
- perforce is a source control software so nothing related to cryblend.
- The second error says that cgf file was not generated, rc.exe was processing the dae file but found some error so finally the cgf file was not generated, doesn't exist. Try to check Lumberyard\Tools\rc\rc.log after export with cryblend, it should show you the problem with your geometry.

**Comment by niclasschult** [comment]
Thanks for your reply!
1. Thanks for the information, I never heard of it before. I read at the AWS forums, that 3ds-max users get similar warnings on export, so this might just be an early quirk of LumberYard,

2. I tried to find the rc.log file, but it seems that the folder structure is different than it was before. I found the files rc_log.log and rc_log_errors.log in dev/bin64/rc , but they didn't tell me much more than the system console. rc_log.log seemed to be exactly the same as the output of the system console, while rc_log_errors.log showed the error message, that the cgf couldn't be found in isolation:

"E: 1>  0:04 E:\lumberyard-1.0-143307e-pc\dev\SamplesProject\Objects\blender\cube\cube.cgf
E: 1>  0:04 CStatCGFCompiler::Process: Failed to load geometry file E:\lumberyard-1.0-143307e-pc\dev\SamplesProject\Objects\blender\cube\cube.cgf: File E:\lumberyard-1.0-143307e-pc\dev\SamplesProject\Objects\blender\cube\cube.cgf failed to open for reading
E: 1>  0:04 Failed to convert file E:\lumberyard-1.0-143307e-pc\dev\SamplesProject\Objects\blender\cube\cube.cgf"

It's very possible that I am just doing something wrong, this is the first time I use CryBlend.

Thanks again!

**Comment by ochounos** [comment]
Seems that there is a problem in your dae file. Try to drop the dae file to rc.exe directly and check again rc.log.

Review that you have added your mesh to one ExportNode (i.e. cube), you have assigned one material following the notation (cube__001__material__physDefault) and you have added an UV map to the mesh. Just to be sure, apply All transformations to your mesh and try again to export.

**Comment by niclasschult** [comment]
If I directly drag the dae onto rc.exe, I do not see any error message in the rc_log.log, but the resource compiler just stopped after loading the dae:
" 1>  0:04 Finished loading 'E:\lumberyard-1.0-143307e-pc\dev\SamplesProject\Objects\ blender\cube\cube.dae'
   1>  0:04 
      1 file processed in 0.0 sec.
      Memory: working set 15.5Mb (peak 17.7Mb), pagefile 22.0Mb (peak 25.8Mb)
      Finished at: Sun Feb 14 23:17:09 2016
      0 errors, 1 warnings."

I reviewed all the settings you mentioned and even setup the project again, but still run into the same problem. 

I attached a few screenshots as well as the log files, maybe you can see if I made a mistake (if you have the time, of course)

![screen1](https://cloud.githubusercontent.com/assets/5258325/13036850/18fa823c-d373-11e5-99ef-8ce2bfceada2.jpg)
![screen2](https://cloud.githubusercontent.com/assets/5258325/13036866/4a96bd38-d373-11e5-8178-1e0abf2faa14.jpg)
![screen3](https://cloud.githubusercontent.com/assets/5258325/13036870/55cc50c8-d373-11e5-9b76-f4c326225787.jpg)
![screen4](https://cloud.githubusercontent.com/assets/5258325/13036873/5d0a944e-d373-11e5-91d8-110c74028c1c.jpg)


[rc_log.log.txt](https://github.com/travnick/CryBlend/files/129947/rc_log.log.txt)
[rc_log_errors.log.txt](https://github.com/travnick/CryBlend/files/129948/rc_log_errors.log.txt)

**Comment by ochounos** [comment]
I was trying also, your blender settings are ok. I have reproduced exactly the same issues as you. The same blender file works in cryengine, but is not working in lumberyard. Seems that amazon has changed something. Lumberyard is in beta stage, maybe they will fix some problems and the next version is working already.

Seems to me that it's a lumberyard problem and not yours. The dae is processed without any warning or error but the cgf file is not generated.

I will try different configurations, just in case that it can be solved from cryblend side but seems that it's on lumberyard side. I'm sorry for the time you spend on it.

**Comment by niclasschult** [comment]
Yes, this definitely sounds like LumberYard changed something in the resource compiler. I read at the forums at Amazon that the LumberYard-developers are already looking at CryBlend, in order to provide a better asset pipeline for Blender users. So hopefully they will fix it in the foreseeable future

**Comment by motorsep** [comment]
Did you guys report it to Lumberyard devs?

**Comment by niclasschult** [comment]
No, not yet, sorry

**Comment by trafflux** [comment]
I am very interested in having a working Blender export option for Lumberyard as are TONS of people on forums. I just happened to stumble across this page and was quite thrilled until I ran into the same issue of the cgf file disappearing. I wish I could help with the scripting but its way out of my depth. Anyways I'd expect this github project to explode with activity soon.  Thanks for the hard work travnick and please stay motivated!

**Comment by ochounos** [comment]
@trafflux Amazon says that they will implement full fbx pipeline import soon so maybe you will not need CryBlend for Lumberyard. It could be much better because it will be official tool for Blender as opposite of CryBlend which is not official for Crytek neither Amazon.

In the meantime we are trying to make it working too on Lumberyard. We had a look already, but no luck at the moment because rc.exe is not throwing any error, just not generating the expected .cgf file.

**Comment by travnick** [comment]
In the other hand, since we have access to rc.exe source we are able to fix it, provide more diagnostic and still have compatibility with output file that CryEngine/Lumberyard requires.

**Comment by ochounos** [comment]
@travnick As I understood, amazon is planning to change formats, but right now they should use the same format. It seems to me that the problem is a bug in the rc.exe code. We have source code but no documentation, no changelog and no source code changes. Seems far to me to fix potential problems from rc.exe code that could be nothing related to CryBlend. I think we should wait to see if Lumberyard fixes the problem (don't forget that it's still beta version) and see how Lumberyard goes to keep source code changes, documentation for developers and so on.

**Comment by trafflux** [comment]
Did you guys happen to try a rc.exe /help to get a list of the usage and commands to see if it differs from the old version?  Also could we just use the old CryTek rc.exe as a temp solution?

**Comment by ochounos** [comment]
@trafflux Could you try to compare both crytek rc.exe and lumberyard rc.exe help? You don't need any knowledge about python or c++.
I can confirm that new cryblend version (will be released very soon) works with current crytek rc.exe. Didn't try to import .cgf files to Lumberyard, personally I don't use Lumberyard. Could you just try to import some of your old .cgf files from Crytek to Lumberyard? Is it working?

**Comment by trafflux** [comment]
I never used the Crytek engine before, sorry. I'd be happy to test for you if you have any old cgf's.

**Comment by ochounos** [comment]
At the moment, you can use fbx importer to bring your meshes from Blender to Lumberyard. Here there is a video from James Brady showing how to do it:
https://www.youtube.com/watch?v=eg2neHvbfpQ

**Comment by trafflux** [comment]
Interesting, I don't know how I missed that. I'm not too versed with FBX files so I'll have to figure out what the limitations are as far as materials/textures/animations/rigging etc.  Thanks for the find ochounos, now I can get busy learning Lumberyard.

**Comment by ochounos** [comment]
Right now, if it's the same as cryengine, you can import only rigid meshes (no geometric animation, no characters, skins or skeleton animations). You can create materials in the lumberyard editor and you can create proxies with designer editor too, they don't need to be included in the fbx file.

**Comment by niclasschult** [comment]
maybe this helps. i have not tried it yet though
https://gamedev.amazon.com/forums/questions/2277/collada-scene-node-naming-convention-for-lumberyar.html

**Comment by dwhite4** [comment]
Sorry guys, been away for a while.  Looks like @niclasschult is on to something though.  It appears they have changed the node naming scheme.  This is a relatively simple fix.  I will make it and commit the changes for testing.

**Comment by ochounos** [comment]
Thank you @niclasschult to show us the way. The problem is solved now and Cryblend will work with LumberYard too. Right now the changes have not been applied still to our main branch but CryBlend will be working for LumberYard in the next official release.

**Comment by niclasschult** [comment]
This is fantastic news :) , I will try it later tonight

**Comment by ochounos** [comment]
@niclasschult The code has not been applied to any of the official branches yet. You cannot try it yet. In the meantime, and only in the meantime, if you want, you could try my branch "ochounos" [https://github.com/ochounos/CryBlend/tree/ochounos](url) which have such changes (and other future features) but keep in mind that this branch is **NOT OFFICIAL**, just my branch, so don't complain CryBlend about any bug found there.

**Comment by niclasschult** [comment]
@ochounos 
Thanks very much for your reply!
Sorry, I misunderstood, I thought you uploaded a new version, my bad. 
But thanks very much for the link to your develop-branch. Can not wait to try it out. 

And don't worry, I won't complain :)

**Comment by niclasschult** [comment]
The export of static meshes to Lumberyard works with your version, very promising :) I will try something more complex tomorrow. Thanks so much for this!

**Comment by ochounos** [comment]
@niclasschult Thank you for your feedback. glad to know that it's working. Let me know if you find any problem, I will try to fix it asap.

**Comment by dwhite4** [comment]
How do you like this GUI?  Is this better or worse?

**Comment by ochounos** [comment]
I prefer the another one because exporting to LumberYard is just another option, and it that case seems that we have 50% for cryengine and 50% for lumberyard. Could make sense if changing this option changes also the below options to more specific export, which is not the case.

Personally I'm not using Lumberyard and I'm not planning to spend too much time keeping compatibility. Let's see how LumberYard evolves, they promised fbx full import so maybe cryblend is not needed for their users. I think this option is a "in the meantime" feature. Showing on the top seems that we are mantaining both at the same level which is not true, we are focused on CryEngine right now. Just my two cents.

**Comment by dwhite4** [comment]
Good point, I think this way is more visually appealing, but, like you said, it gives the impression that we support each engine 50-50.  It may be best to leave it as a check box for now.  Thanks for your feedback.

**Comment by ochounos** [comment]
Issue fixed in on 29th February commit. No bugs reported. Reopen if bug found, otherwise we can close this issue.

**Comment by dwhite4** [comment]
Sounds good!

**Comment by SalahAdDin** [comment]
For CryEngine v?

**Comment by ochounos** [comment]
The current official version works with CryEngine V already. Did you try it? Did you find any problem?
When the new official version is released will be working with CryEngine V too. I'ts our main focus, to work with CryEngine. Also, we made compatible with Lumberyard.

**Comment by klwb80** [comment]
Could someone clarify for me how to import an object into lumberyard? I've tried using the ochounos version of the io_export but I still get just a .dae file and no .cgf. I can't use the fbx importer because my object then doesn't have a collision mesh and therefore cannot assign buoyancy

**Comment by niclasschult** [comment]
Did you use the"Lumberyard" Checkbox on export?

**Comment by klwb80** [comment]
I've never seen a lumberyard checkbox when exporting, I just click export
to node. Where would I see/find this option?

**Comment by ochounos** [comment]
Good point @niclasschult 

@klwb80 If oyu are using the version of my branch, you should have such option in the export panel (left down when choosing where to export the scene). Try to find the checkbox and export again. It should work. In case that you have problems exporting, try to check the log file to find out what could be the problem.

**Comment by klwb80** [comment]
It exported as a .cgf time which is great, but I'm assuming it still doesn't have a collision mesh as it isn't affected by gravity or buoyancy. Any suggestions?

**Comment by ochounos** [comment]
Create your proxy, you have some options in the menu to do that. It's created as it was in the official version, no changes on it, just fixed bugs on proxy.

You can check in cryengine if your entity has collision or not. Also if you are trying to achieve physics, be sure that yout entity has unchecked "resting" option or physics will not affect it.

**Comment by klwb80** [comment]
My issue is that I really have no idea how to use blender. I imported my object, added a material, added a uv map, added an export node .. what type of proxy should I be adding? I feel like I've done several things, none of which are working

**Comment by klwb80** [comment]
What I'm doing works for the basic cube shape but when I import the file I'd like to use (a boat), when I take the same steps in blender and export to lumberyard the boat won't float but the cube will. Am I doing something wrong by importing the object? I've imported it as a .obj and a .3ds file and neither work after export

**Comment by ochounos** [comment]
I don't know about Lumberyard because I'm not using it, but I think it must be an entity BasicEntity to support physics. Try to check the type of entity of the cube and replicate the properties to achieve the same effect. If you don't add a proxy, at least in cryengine, rc.exe will add a proxy for you.

Please check the Lumberyard docs or ask in their forums to find a way to solve your problem. Unfortunately it's out of my knowledge.

**Comment by niclasschult** [comment]
Took me long enough, but I now can confirm that CryBlend is able to export static meshes, skeletons, animations as well as skins to Lumberyard (using Lumberyard 1.2 Beta). I still have some issues with the skins in the engine, but I am pretty sure that these are caused by the particular characters and animations I am trying to import.

**Comment by muhammadmadi** [comment]
this is very good news niclasschult
